### ISSUE TITLE
If --flags is not passed, autobisect chokes

### ISSUE THREAD

**Issue by tomrittervg** [MozillaSecurity/autobisect#34]
```
poetry run python -m autobisect js -d -a testcase.js
[2020-11-06 10:36:31] Begin bisection...
[2020-11-06 10:36:31] > Start: 478c5bf5ccb37d3a38bda833a8751fd43db58ff1 (20191108171434)
[2020-11-06 10:36:31] > End: 41effaf024a55426f4486278364dea1117ed6571 (20201106093443)
[2020-11-06 10:36:31] Attempting to verify boundaries...
[2020-11-06 10:36:31] Testing build 478c5bf5ccb37d3a38bda833a8751fd43db58ff1 (20191108171434)
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tom/Documents/moz/autobisect/autobisect/__main__.py", line 8, in <module>
    sys.exit(main(parse_args()))
  File "/home/tom/Documents/moz/autobisect/autobisect/main.py", line 88, in main
    result = bisector.bisect()
  File "/home/tom/Documents/moz/autobisect/autobisect/bisect.py", line 267, in bisect
    verified = self.verify_bounds()
  File "/home/tom/Documents/moz/autobisect/autobisect/bisect.py", line 346, in verify_bounds
    start_result = self.test_build(self.start)
  File "/home/tom/Documents/moz/autobisect/autobisect/bisect.py", line 338, in test_build
    return self.evaluator.evaluate_testcase(build_path)
  File "/home/tom/Documents/moz/autobisect/autobisect/evaluators/js/js.py", line 114, in evaluate_testcase
    for flag in self.flags:
TypeError: 'NoneType' object is not iterable
```

It expects something, even if it's just `--flags "`

**Comment by pyoor** [comment]
@tomrittervg thanks for the issue and sorry it took me so long to address it.  I completely missed this issue until today.
